// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// siapopConstant
int siapopConstant(Rcpp::CharacterVector input);
RcppExport SEXP siapopr_siapopConstant(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(siapopConstant(input));
    return rcpp_result_gen;
END_RCPP
}
// siapopSimple
int siapopSimple(Rcpp::CharacterVector input);
RcppExport SEXP siapopr_siapopSimple(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(siapopSimple(input));
    return rcpp_result_gen;
END_RCPP
}
// siapopTimeDep
int siapopTimeDep(Rcpp::CharacterVector input);
RcppExport SEXP siapopr_siapopTimeDep(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(siapopTimeDep(input));
    return rcpp_result_gen;
END_RCPP
}
