# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' siapopConstant
#'
#' SIApop for time-homogeneous populations. Simulates a
#' Birth-Death-Mutation process simulation for infinite-allele
#' model with random fitness contributions using the Gillespie Algorithm and
#' outputs data to the location of \code{output_dir}.
#'
#' The infinite-allele birth death process assumes anytime a mutation that
#' occurs, it is unique and not seen in the population. \code{siapopConstant}
#' can generates an infinite-allele birth-death time homogeneous process along
#' with additional scenarios that affect new clones.
#'
#' A fitness distribution is provided so that the birth rate of new clones is
#' additive with the additional fitness coming from this distribution. The
#' mutation distribution has a similar effect on the mutation rate of a new
#' clone. The punctuated parameters assume a new clone may arise that contains
#' multiple new alleles instead of a single new allele. These clones have
#' different fitnesses as well and a Poisson number of new alleles. The
#' epistatic parameters refer to a simple epistatic model where a change in
#' fitness occurs in a clone when it reaches \code{epistatic_mutation_thresh}
#' total mutations.
#'
#' The process can be run with defaults that result in a simple model without
#' mutations. The defaults for most parameters that would affect fitness of
#' new clones are set such that they have no effect on the process.
#'
#' Simulations are output as text files and input can be in the form of text
#' files or a comma-delimeted input file. Currently input for the ancestors
#' requires a text file.
#'
#' @param tot_life total lifetime to run a simulation for
#' @param max_pop maximum population to stop simulation
#' @param start_time time index to begin each simulation
#' @param ancestors number of ancestors in a clone to initialize simulation
#' @param ancestor_clones number of ancestor clones each containing
#'   \code{ancestors} individuals to initialize simulation with
#' @param num_sims number of simulations to run
#' @param allow_extinction if TRUE then each simulation restarts when
#'   extinction occurs. The run counter is incremented and the data is still
#'   recorded in \emph{timedata.txt}
#' @param is_custom_model (not implemented yet) allows user to provide a shared
#'   object file to advance the clone
#' @param num_samples number of single cell samples to take from each
#'   simulation
#' @param sample_size size of each sample of single cells
#' @param detection_threshold minimum threshold to report clones. If a clone is
#'   below minimum its number is added to its parent count.
#' @param observation_frequency the frequency of time to output the current
#'   population to \emph{timedata.txt}
#' @param observation_times a vector of specific time points to output the
#'   current population to \emph{timedata.txt}
#' @param birth_rate ancestor birth rate
#' @param death_rate ancestor birth rate
#' @param mutation_prob ancestor mutation probability, probability that a
#' daughter is a new mutant allele
#' @param distribution_function one of "doubleexp", "normal", "uniform", or
#'   custom
#' @param custom_distribution_file file name of a .so library built from a
#'   C++ function "customdist"
#' @param alpha_fitness fitness distribution (right-side) rate parameter. When
#'   a new clone arises, the fitness of the new clone is a double exponential
#'   with the positive side having rate \code{alpha}
#' @param beta_fitness fitness distribution (left-side) rate parameter. When a
#'   new clone arises, the fitness of the new clone is a double exponential
#'   with the negative side having rate \code{beta}
#' @param pass_prob probability of no change in fitness
#' @param upper_fitness upper bound to fitness distribution
#' @param lower_fitness lower bound to fitness distribution
#' @param alpha_mutation mutation distribution alpha parameter. A new clone
#'   can have a new mutation rate coming from a distribution with parameters
#'   \code{alpha} and \code{beta}.
#' @param beta_mutation mutation distribution beta parameter. A new clone can
#'   have a new mutation rate coming from a distribution with parameters
#'   \code{alpha} and \code{beta}
#' @param trace_ancestry if \code{TRUE} then \emph{clonedata.txt} reports the
#'   parent clone id and time
#' @param count_alleles if \code{TRUE} then reports the number of cells with
#'   allele equal to the final id of the clone. For example, a single ancestor
#'   should have an allele frequency equal to the sum of the current living
#'   population.
#' @param punctuated_prob probability that a new clone has a burst of multiple
#'   mutations
#' @param poisson_param parameter of a poisson distribution used to determine
#'   the number of mutations in a new clone given a burst occurs
#' @param punctuated_multiplier = given a burst occurs in the new clone, the
#'   fitness is multiplied by this amount to affect the fitness distribution.
#' @param punctuated_advantageous_prob the probability that a punctuated clone
#'   has a positive fitness
#' @param epistatic_mutation_thresh = number of mutations before an epistatic
#'   event occurs affecting the fitness
#' @param epistatic_multiplier = given an epistatic event occurs, the fitness
#'   is multiplied by this amount
#' @param input_file input character vector of input file
#' @param output_dir input character vector of output location
#' @param ancestor_file input character vector of ancestor file
#' @examples
#' \dontrun{
#' # Use default values
#' siapopConstant()
#' siapopConstant(outputdir = "./")
#' siapopConstant(ancestor_file = "./ancestors.txt")
#' siapopConstant(tot_life = 10, max_pop = 1000, birth_rate = 1.1,
#'                death_rate = 0.99, mutation_prob = 0.01,
#'                allow_extinction = FALSE, num_sims = 1, num_samples = 1,
#'                alpha_fitness = 100, beta_fitness = 100,
#'                sample_size = 100, observation_times = c(1, 5, 10))
#' }
#' @export
siapopConstant <- function(tot_life = 40000.0, max_pop = 10000L, start_time = 0.0, ancestors = 1L, ancestor_clones = 1L, num_sims = 1L, allow_extinction = TRUE, is_custom_model = FALSE, num_samples = 0L, sample_size = 0L, detection_threshold = 0.0, observation_frequency = 0.0, observation_times = NULL, birth_rate = 1.5, death_rate = 1.0, mutation_prob = 0.0, fitness_distribution = NULL, custom_distribution_file = NULL, alpha_fitness = 0.0, beta_fitness = 0.0, pass_prob = 1.0, upper_fitness = 0.0, lower_fitness = 0.0, alpha_mutation = 0.0, beta_mutation = 0.0, trace_ancestry = TRUE, count_alleles = TRUE, punctuated_prob = 0.0, poisson_param = 1.0, punctuated_multiplier = 1.0, punctuated_advantageous_prob = 1.0, epistatic_mutation_thresh = 1.0, epistatic_multiplier = 1.0, seed = NULL, input_file = NULL, output_dir = NULL, ancestor_file = NULL) {
    .Call('siapopr_siapopConstant', PACKAGE = 'siapopr', tot_life, max_pop, start_time, ancestors, ancestor_clones, num_sims, allow_extinction, is_custom_model, num_samples, sample_size, detection_threshold, observation_frequency, observation_times, birth_rate, death_rate, mutation_prob, fitness_distribution, custom_distribution_file, alpha_fitness, beta_fitness, pass_prob, upper_fitness, lower_fitness, alpha_mutation, beta_mutation, trace_ancestry, count_alleles, punctuated_prob, poisson_param, punctuated_multiplier, punctuated_advantageous_prob, epistatic_mutation_thresh, epistatic_multiplier, seed, input_file, output_dir, ancestor_file)
}

#' siapopSimple
#'
#' SIApop for non-mutating processes. Runs an exact process by simulating
#' binomial and negative binomial random values at each time step. The process
#' is only ran for a total length of time since the simulation is exact during
#' that time instead of running until a specific population size.
#'
#' Simple birth-death processes can be simulated exactly by generating a
#' binomial random variable to determine the number of ancestors of a specific
#' clone that give rise to descendant, then a negative binomial random
#' variable to determine the total number of descendant that arise out of those
#' replicating ancestors. This can be done for each ancestor clone with
#' various rates. Mutation is not permitted in this scheme.
#'
#' Simulations are output as text files and input can be in the form of text
#' files or a comma-delimeted input file. Currently input for the ancestors
#' requires a text file.
#'
#' @param tot_life total lifetime to run a simulation for
#' @param ancestors number of ancestors in a clone to initialize simulation
#' @param ancestor_clones number of ancestor clones each containing
#'   \code{ancestors} individuals to initialize simulation with
#' @param num_sims number of simulations to run
#' @param allow_extinction if TRUE then each simulation restarts when
#'   extinction occurs. The run counter is incremented and the data is still
#'     recorded in \emph{timedata.txt}
#' @param num_samples number of single cell samples to take from each
#'   simulation
#' @param sample_size size of each sample of single cells
#' @param detection_threshold minimum threshold to report clones. If a clone is
#'   below minimum its number is added to its parent count.
#' @param input input character vector of input file
#' @param output_dir input character vector of output location
#' @param ancestor_file input character vector of ancestor file
#' @param birth_rate ancestor birth rate
#' @param death_rate ancestor birth rate
#' @examples
#' \dontrun{
#' # Use default values
#' siapopSimple()
#' siapopSimple(input_file = "./input.txt, "output_dir = "./",
#'              ancestor_file = "ancestors.txt")
#' siapopSimple(tot_life = 5, ancestors = 10, ancestor_clones = 5,
#'              num_sims = 1, allow_extinction = FALSE,
#'              detection_threshold = 0, birth_rate = 1.1, death_rate = 1)
#' }
#' @export
siapopSimple <- function(tot_life = 40000.0, ancestors = 1L, ancestor_clones = 1L, num_sims = 1L, num_samples = 0L, sample_size = 0L, allow_extinction = TRUE, detection_threshold = 0.0, birth_rate = 1.5, death_rate = 1.0, seed = NULL, input_file = NULL, output_dir = NULL, ancestor_file = NULL) {
    .Call('siapopr_siapopSimple', PACKAGE = 'siapopr', tot_life, ancestors, ancestor_clones, num_sims, num_samples, sample_size, allow_extinction, detection_threshold, birth_rate, death_rate, seed, input_file, output_dir, ancestor_file)
}

#' siapopTimeDep
#'
#' SIApop for time-dependent processes. Time-Dependent Birth-Death-Mutation
#' process simulation for infinite-allele model with random fitness
#' contributions using the Gillespie Algorithm. Imports data, runs SSA and
#' outputs to \emph{output_dir}.
#'
#' The infinite-allele birth death process assumes anytime a mutation that
#' occurs, it is unique and not seen in the population. \code{siapopConstant}
#' can generates an infinite-allele birth-death time inhomogeneous process
#' along with additional scenarios that affect new clones. The time dependent
#' functions are provided and explained in the details.
#'
#' A fitness distribution is provided so that the birth rate of new clones is
#' additive with the additional fitness coming from this distribution. The
#' mutation distribution has a similar effect on the mutation rate of a new
#' clone. The punctuated parameters assume a new clone may arise that contains
#' multiple new alleles instead of a single new allele. These clones have
#' different fitnesses as well and a Poisson number of new alleles. The
#' epistatic parameters refer to a simple epistatic model where a change in
#' fitness occurs in a clone when it reaches \code{epistatic_mutation_thresh}
#' total mutations.
#'
#' The process can be run with defaults that result in a simple model without
#' mutations. The defaults for most parameters that would affect fitness of
#' new clones are set such that they have no effect on the process.
#'
#' Time dependent functions and their coefficients (x_0, x_1, x_2, ...) can be
#' provided according to the following:
#'
#' 0: constant f(t) = \eqn{x_1}
#'
#' 1: linear f(t) = \eqn{max(x_1 + x_2 t, x_3)}
#'
#' 2: logistic f(t) = \eqn{x_1 + (x2 - x_1)((1 + x_5 \times exp \{(-x_3(t - x_6))\})^{1 / x_4})}
#'
#' 3: Gompertz Growth f(t) = x_1 + x_3 exp\{-x_2 t\}
#'
#' Simulations are output as text files and input can be in the form of text
#' files or a comma-delimeted input file. Currently input for the ancestors
#' requires a text file.
#'
#' @param tot_life total lifetime to run a simulation for
#' @param max_pop maximum population to stop simulation
#' @param start_time time index to begin each simulation
#' @param ancestors number of ancestors in a clone to initialize simulation
#' @param ancestor_clones number of ancestor clones each containing
#'   \code{ancestors} individuals to initialize simulation with
#' @param num_sims number of simulations to run
#' @param allow_extinction if TRUE then each simulation restarts when
#'   extinction occurs. The run counter is incremented and the data is still
#'   recorded in \emph{timedata.txt}
#' @param is_custom_model (not implemented yet) allows user to provide a
#'   shared object file to advance the clone
#' @param num_samples number of single cell samples to take from each
#'   simulation
#' @param sample_size size of each sample of single cells
#' @param detection_threshold minimum threshold to report clones. If a clone
#'   is below minimum its number is added to its parent count.
#' @param observation_frequency the frequency of time to output the current
#'   population to \emph{timedata.txt}
#' @param observation_times a vector of specific time points to output the
#'   current population to \emph{timedata.txt}
#' @param birth_function an integer to match the time dependent birth function
#'   0 = constant: 1 = linear, 2 = logistic, 3 = Gompertz growth,
#'   4 = custom (not yet implemented)
#' @param birth_coefs vector of coefficients associated with
#'   \code{birth_function}. See Details.
#' @param death_function an integer to match the time dependent birth function
#'   0 = constant: 1 = linear, 2 = logistic, 3 = Gompertz growth,
#'   4 = custom (not yet implemented)
#' @param death_coefs vector of coefficients associated with
#'   \code{death_function}. See Details.
#' @param mutation_prob ancestor mutation probability, probability that a
#'   daughter is a new mutant allele
#' @param distribution_function one of "doubleexp", "normal", "uniform", or
#'   "custom"
#' @param custom_distribution_file file name of a .so library built from a
#'   C++ function "customdist"
#' @param alpha_fitness fitness distribution (right-side) rate parameter. When
#'   a new clone arises, the fitness of the new clone is a double exponential
#'   with the positive side having rate \code{alpha}
#' @param beta_fitness fitness distribution (left-side) rate parameter. When a
#'   new clone arises, the fitness of the new clone is a double exponential
#'   with the negative side having rate \code{beta}
#' @param pass_prob probability of no change in fitness
#' @param upper_fitness upper bound to fitness distribution
#' @param lower_fitness lower bound to fitness distribution
#' @param alpha_mutation mutation distribution alpha parameter. A new clone
#'   can have a new mutation rate coming from a distribution with parameters
#'   \code{alpha} and \code{beta}.
#' @param beta_mutation mutation distribution beta parameter. A new clone can
#'   have a new mutation rate coming from a distribution with parameters
#'   \code{alpha} and \code{beta}
#' @param trace_ancestry if \code{TRUE} then \emph{clonedata.txt} reports the
#'   parent clone id and time
#' @param count_alleles if \code{TRUE} then reports the number of cells with
#'   allele equal to the final id of the clone. For example, a single ancestor
#'   should have an allele frequency equal to the sum of the current living
#'   population.
#' @param punctuated_prob probability that a new clone has a burst of multiple
#'   mutations
#' @param poisson_param parameter of a poisson distribution used to determine
#' the number of mutations in a new clone given a burst occurs
#' @param punctuated_multiplier = given a burst occurs in the new clone, the
#' fitness is multiplied by this amount to affect the fitness distribution.
#' @param punctuated_advantageous_prob the probability that a punctuated clone
#'   has a positive fitness
#' @param epistatic_mutation_thresh = number of mutations before an epistatic
#'   event occurs affecting the fitness
#' @param epistatic_multiplier = given an epistatic event occurs, the fitness
#'   is multiplied by this amount
#' @param input_file character vector of input file
#' @param output_dir input character vector of output location
#' @param ancestor_file input character vector of ancestor file
#' @examples
#' \dontrun{
#' # Use default values
#' siapopTimeDep()
#' siapopTimeDep(outputdir = "./", birth_function = 1, death_function = 0
#'                birth_params = c(-1, 0, 0.01), death_params = 0.5)
#' siapopTimeDep(tot_life = 10, max_pop = 1000,  birth_function = 1,
#'                death_function = 0, birth_params = c(-1, 0, 0.01),
#'                death_params = 0.5, death_rate = 0.99, mutation_prob = 0.01,
#'                allow_extinction = FALSE, num_sims = 1, num_samples = 1,
#'                alpha_fitness = 100, beta_fitness = 100,
#'                sample_size = 100, observation_times = c(1, 5, 10))
#' }
#' @export
siapopTimeDep <- function(tot_life = 40000.0, max_pop = 10000L, start_time = 0.0, ancestors = 1L, ancestor_clones = 1L, num_sims = 1L, allow_extinction = TRUE, is_custom_model = FALSE, num_samples = 0L, sample_size = 0L, detection_threshold = 0.0, observation_frequency = 0.0, observation_times = NULL, birth_function = 0L, birth_coefs = as.numeric( c(1.0, 0.0, 1.0)), death_function = 0L, death_coefs = as.numeric( c(1.0, 0.0, 1.0)), mutation_prob = 0.0, fitness_distribution = NULL, custom_distribution_file = NULL, alpha_fitness = 0.0, beta_fitness = 0.0, pass_prob = 1.0, upper_fitness = 0.0, lower_fitness = 0.0, alpha_mutation = 0.0, beta_mutation = 0.0, trace_ancestry = TRUE, count_alleles = TRUE, punctuated_prob = 0.0, poisson_param = 1.0, punctuated_multiplier = 1.0, punctuated_advantageous_prob = 1.0, epistatic_mutation_thresh = 1.0, epistatic_multiplier = 1.0, seed = NULL, input_file = NULL, output_dir = NULL, ancestor_file = NULL) {
    .Call('siapopr_siapopTimeDep', PACKAGE = 'siapopr', tot_life, max_pop, start_time, ancestors, ancestor_clones, num_sims, allow_extinction, is_custom_model, num_samples, sample_size, detection_threshold, observation_frequency, observation_times, birth_function, birth_coefs, death_function, death_coefs, mutation_prob, fitness_distribution, custom_distribution_file, alpha_fitness, beta_fitness, pass_prob, upper_fitness, lower_fitness, alpha_mutation, beta_mutation, trace_ancestry, count_alleles, punctuated_prob, poisson_param, punctuated_multiplier, punctuated_advantageous_prob, epistatic_mutation_thresh, epistatic_multiplier, seed, input_file, output_dir, ancestor_file)
}

