# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' SIApop for time-homogeneous populations
#'
#' @param input input character vector of input file
#' @param output_dir input character vector of output location
#' @param ancestor_file input character vector of ancestor file
#' @export
siapopConstant <- function(input = NULL, output_dir = NULL, ancestor_file = NULL) {
    .Call('siapopr_siapopConstant', PACKAGE = 'siapopr', input, output_dir, ancestor_file)
}

#' SIApop for non-mutating processes
#'
#' @param input input character vector of input file
#' @param output_dir input character vector of output location
#' @param ancestor_file input character vector of ancestor file
#' @export
siapopSimple <- function(input = NULL, output_dir = NULL, ancestor_file = NULL) {
    .Call('siapopr_siapopSimple', PACKAGE = 'siapopr', input, output_dir, ancestor_file)
}

#' SIApop for time-dependent processes.
#'
#' @param input input character vector of input file
#' @param output_dir input character vector of output location
#' @param ancestor_file input character vector of ancestor file
#' @export
siapopTimeDep <- function(input = NULL, output_dir = NULL, ancestor_file = NULL) {
    .Call('siapopr_siapopTimeDep', PACKAGE = 'siapopr', input, output_dir, ancestor_file)
}

