# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

siapopConstant <- function(input) {
    .Call('siapopr_siapopConstant', PACKAGE = 'siapopr', input)
}

siapopSimple <- function(input) {
    .Call('siapopr_siapopSimple', PACKAGE = 'siapopr', input)
}

siapopTimeDep <- function(input) {
    .Call('siapopr_siapopTimeDep', PACKAGE = 'siapopr', input)
}

